events {}

http {
    upstream fraud_cluster {
        server fraud_api_1:8080;
        server fraud_api_2:8080;
    }

    server {
        listen 9999;

        location /ready {
            proxy_pass http://fraud_cluster;
        }

        location /fraud-score {
            proxy_pass http://fraud_cluster;
        }
    }
}
